### ISSUE TITLE
[Feature]: Background push handler for silent push notifications

### ISSUE THREAD

**Issue by mcalc001** [braze-inc/braze-react-native-sdk#238]
### What problem are you facing?

Braze doesn't give out the box solution for background & Quit state messages. Specifically the ability to detect Silent push notification's when in background/quit state.

### Workarounds

Currently the only work around would be to create our own react native bridge or to integrate another push notification provider to handle silent push notifications.

### Ideal Solution

Our ideal solution would be the introduction of a background push handler in Braze, specifically designed to handle silent push notifications. This would mimic the functionality of [setBackgroundMessageHandler](https://rnfirebase.io/messaging/usage#background--quit-state-messages) currently available from @react-native-firebase

**Comment by jerielng** [comment]
Hey @mcalc001, thanks for raising this. Our handler methods aren't able to support background messages because they specifically notify of push updates via Braze, which require the SDK to be launched and running to be processed.

It's something we can look deeper into--if you wouldn't mind, could you file some product feedback [here](https://dashboard.braze.com/resources/roadmap) so we can assess how to prioritize this? Thank you!

**Comment by jerielng** [comment]
Hey @mcalc001, version [10.0.0](https://github.com/braze-inc/braze-react-native-sdk/releases/tag/12.0.0) of our React Native SDK now supports push received events on iOS for the following scenarios:
* a push is received in the foreground
* a push with `content-available=1` is received in the background.

Due to platform limitations, we cannot process push received events while the app is terminated (not in memory).

We will shortly be releasing updated documentation [here](https://www.braze.com/docs/developer_guide/platform_integration_guides/react_native/push_notifications/?tab=ios) for more details on this usage.

Thank you!
